# Generated by Django 5.2 on 2026-02-18 14:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tipe', models.CharField(blank=True, max_length=100, null=True)),
                ('total_kursi', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('persen_diskon', models.IntegerField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nama_lengkap', models.CharField(blank=True, max_length=255, null=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_ktp', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=20, null=True)),
                ('kota_kab', models.CharField(blank=True, max_length=100, null=True)),
                ('peran', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('user', 'User')], default='user', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asal', models.CharField(max_length=255)),
                ('tujuan', models.CharField(max_length=255)),
                ('waktu_keberangkatan', models.DateTimeField()),
                ('waktu_kedatangan', models.DateTimeField(blank=True, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='active', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='accounts.bus')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeKomisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_transaksi', models.IntegerField(default=0)),
                ('total_komisi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_setor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='open', max_length=50)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('agen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode_komisi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persen_komisi', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran_pembeli', models.CharField(max_length=20)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('status_pembayaran', models.CharField(default='pending', max_length=20)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jumlah_diskon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('harga_akhir', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jadwal')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemesanan', to=settings.AUTH_USER_MODEL)),
                ('promosi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.promosi')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kursi', models.CharField(max_length=10)),
                ('nama_penumpang', models.CharField(max_length=255)),
                ('ktp_penumpang', models.CharField(blank=True, max_length=50, null=True)),
                ('telepon_penumpang', models.CharField(blank=True, max_length=20, null=True)),
                ('jenis_kelamin_penumpang', models.CharField(blank=True, max_length=20, null=True)),
                ('kode_tiket', models.CharField(max_length=50, unique=True)),
                ('dicetak_pada', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jadwal')),
                ('pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiket', to='accounts.pemesanan')),
            ],
        ),
        migrations.CreateModel(
            name='KomisiAgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persen_komisi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jumlah_komisi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='unsettled', max_length=50)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('agen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komisi', to=settings.AUTH_USER_MODEL)),
                ('tiket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.tiket')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPeriodeKomisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_komisi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='accounts.periodekomisi')),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tiket')),
            ],
        ),
        migrations.CreateModel(
            name='TransferKomisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_transfer', models.DateTimeField(blank=True, null=True)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bukti_file', models.ImageField(blank=True, null=True, upload_to='bukti_setoran/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('divalidasi_pada', models.DateTimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('divalidasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validasi_transfer', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='accounts.periodekomisi')),
            ],
        ),
    ]
