# Generated by Django 5.2 on 2026-02-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promosi',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
