# Generated by Django 6.0.3 on 2026-04-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_promosi_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='promosi',
            name='maksimal_diskon',
            field=models.IntegerField(default=20000),
        ),
    ]
